### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by vorel99** [vorel99/supervised-pandas-profiling#8]
### Variables

- [ ] pridat alerty o vysvetlovani targetove promenne (nejlepsi/nejhorsi sloupce)
- [ ] klasifikace typu 
  - [x] lepe klasifikovat date type
  - [x] klasifikovat plaintext
    - [x]  type (vykreslit pro nej wordcloud)
- [x] oddelit target od ostatnich sloupcu
  - [x] detekce formatu sloupce
- [ ] pridat korelaci s targetem
- [x] odstranit legendu z nahledu grafu
- [x] u grafu vyresit pozici legendy (obcas pres ni nejsou videt nektera cisla)
- [ ] přidat možnost s vypsáním jednotek u grafu (1000->1K)
- [ ] pridat grafy log(odds) (log2(survived/dead))
  - [ ] pridat laplacovu korekci  
  - [ ] upravit nadpis
  - [ ] odecitst prumer populace
  - [x] categorical
  - [x] real

### Interactions
- [ ] pridat prolozeni krivkou
- [ ] rozdelit dle targetu 

### Base Model module
- [ ] vysvetlovaci hodnota promenne (https://scikit-learn.org/stable/auto_examples/ensemble/plot_forest_importances.html)
  - [ ] seradit promenne. 1. target, dale neradit
